FROM alpine/bombardier:latest

ARG CONNECTIONS
ARG TIMEOUT
ARG STRATEGY

ENV CONNECTIONS=${CONNECTIONS}
ENV TIMEOUT=${TIMEOUT}
ENV STRATEGY=${STRATEGY}

COPY . /app
WORKDIR /app

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["./stop.sh", "-c", "${CONNECTIONS}", "-t", "${TIMEOUT}", "-s", "${STRATEGY}"]